[versions]
armeria = "1.29.4"
spring-boot = "3.3.2"
spring-dependency-management = "1.1.6"
kafka = "3.7.0"
kotlin = "1.9.23"
kotlin-coroutine = "1.8.1"
bouncycastle = "1.78.1"
micrometer = "1.13.0"
netty = "4.1.110.Final"
resilience4j = "2.2.0"
protobuf = "0.9.4"
grpc-proto = "1.63.0"
grpc-kotlin = "1.4.1"
protobuf-kotlin = "3.25.3"
jackson-module-kotlin = "2.17.2"
uap-java = "1.6.1"
ktlint = "1.3.1"

[libraries.boms-armeria]
module = "com.linecorp.armeria:armeria-bom"
version.ref = "armeria"

[libraries.boms-micrometer]
module = "io.micrometer:micrometer-bom"
version.ref = "micrometer"

[libraries.boms-netty]
module = "io.netty:netty-bom"
version.ref = "netty"

[libraries.boms-resilience4j]
module = "io.github.resilience4j:resilience4j-bom"
version.ref = "resilience4j"

[libraries.armeria-kotlin]
module = "com.linecorp.armeria:armeria-kotlin"
version.ref = "armeria"

[libraries.armeria-grpc]
module = "com.linecorp.armeria:armeria-grpc"
version.ref = "armeria"

[libraries.armeria-spring-boot3-starter]
module = "com.linecorp.armeria:armeria-spring-boot3-starter"
version.ref = "armeria"

[libraries.armeria-spring-boot3-actuator-starter]
module = "com.linecorp.armeria:armeria-spring-boot3-actuator-starter"
version.ref = "armeria"

[libraries.spring-boot-starter-security]
module = "org.springframework.boot:spring-boot-starter-security"
version.ref = "spring-boot"

[libraries.spring-boot-starter-test]
module = "org.springframework.boot:spring-boot-starter-test"
version.ref = "spring-boot"

[libraries.spring-boot-configuration-processor]
module = "org.springframework.boot:spring-boot-configuration-processor"
version.ref = "spring-boot"

[libraries.spring-boot-starter-validation]
module = "org.springframework.boot:spring-boot-starter-validation"
version.ref = "spring-boot"

[libraries.spring-boot-starter-data-mongodb]
module = "org.springframework.boot:spring-boot-starter-data-mongodb"
version.ref = "spring-boot"

[libraries.kafka]
module = "org.apache.kafka:kafka-clients"
version.ref = "kafka"

[libraries.kotlin-test]
module = "org.jetbrains.kotlin:kotlin-test"
version.ref = "kotlin"

[libraries.kotlin-stdlib]
module = "org.jetbrains.kotlin:kotlin-stdlib"
version.ref = "kotlin"

[libraries.kotlin-reflect]
module = "org.jetbrains.kotlin:kotlin-reflect"
version.ref = "kotlin"

[libraries.kotlin-allopen]
module = "org.jetbrains.kotlin:kotlin-allopen"
version.ref = "kotlin"

[libraries.kotlin-coroutines-core]
module = "org.jetbrains.kotlinx:kotlinx-coroutines-core"
version.ref = "kotlin-coroutine"

[libraries.kotlin-coroutines-test]
module = "org.jetbrains.kotlinx:kotlinx-coroutines-test"
version.ref = "kotlin-coroutine"

[libraries.kotlin-coroutines-debug]
module = "org.jetbrains.kotlinx:kotlinx-coroutines-debug"
version.ref = "kotlin-coroutine"

[libraries.bcprov-jdk18on]
module = "org.bouncycastle:bcprov-jdk18on"
version.ref = "bouncycastle"

[libraries.grpc-stub]
module = "io.grpc:grpc-stub"
version.ref = "grpc-proto"

[libraries.grpc-protobuf]
module = "io.grpc:grpc-protobuf"
version.ref = "grpc-proto"

[libraries.artifact-gen-grpc-java]
module = "io.grpc:protoc-gen-grpc-java"
version.ref = "grpc-proto"

[libraries.grpc-kotlin-stub]
module = "io.grpc:grpc-kotlin-stub"
version.ref = "grpc-kotlin"

[libraries.artifact-gen-grpc-kotlin]
module = "io.grpc:protoc-gen-grpc-kotlin"
version.ref = "grpc-kotlin"

[libraries.protobuf-kotlin]
module = "com.google.protobuf:protobuf-kotlin"
version.ref = "protobuf-kotlin"

[libraries.artifact-protoc]
module = "com.google.protobuf:protoc"
version.ref = "protobuf-kotlin"

[libraries.jackson-module-kotlin]
module = "com.fasterxml.jackson.module:jackson-module-kotlin"
version.ref = "jackson-module-kotlin"

[libraries.uap-java]
module = "com.github.ua-parser:uap-java"
version.ref = "uap-java"

[libraries.ktlint]
module = "com.pinterest.ktlint:ktlint-cli"
version.ref = "ktlint"

[plugins]
spring-boot = {id = "org.springframework.boot", version.ref = "spring-boot"}
spring-dependency-management = {id = "io.spring.dependency-management", version.ref = "spring-dependency-management"}
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
kotlin-allopen = { id = "org.jetbrains.kotlin.plugin.allopen", version.ref = "kotlin" }
protobuf = {id = "com.google.protobuf", version.ref = "protobuf"}
